include $(THEOS)/makefiles/common.mk

TWEAK_NAME = OpenerSpringBoard
OpenerSpringBoard_FILES = SpringBoard.x
OpenerSpringBoard_PRIVATE_FRAMEWORKS = MobileCoreServices
OpenerSpringBoard_EXTRA_FRAMEWORKS = Cephei Opener
OpenerSpringBoard_CFLAGS = -include ../Global.h -fobjc-arc

include $(THEOS_MAKE_PATH)/tweak.mk
